#$(document).ready ->
#  $('#example').DataTable
#    'processing': true
#    'serverSide': true
#    'ajax':
#      'url': 'wines/table/'
#      'type': 'POST'
#    'columns': [
#      {
#        'data': '_id'
#        'bVisible': false
#      }
#      {'data': 'name'}
#      {'data': 'category'}
#      {'data': 'price'}
#      {'data': 'hits',}
#      {'data': 'sequence'}
#      {'data': 'status'}
#      {'data': 'user_name'}
#      {'data': null}
#    ]
#    'sPaginationType': 'full_numbers'
#    'oLanguage':
#      'sProcessing': '正在加载中......'
#      'sLengthMenu': '每页显示 _MENU_ 条记录'
#      'sZeroRecords': '对不起，查询不到相关数据！'
#      'sEmptyTable': '表中无数据存在！'
#      'sInfo': '当前显示 _START_ 到 _END_ 条，共 _TOTAL_ 条记录'
#      'sInfoFiltered': '数据表中共为 _MAX_ 条记录'
#      'sSearch': '搜索'
#      'oPaginate':
#        'sFirst': '首页'
#        'sPrevious': '上一页'
#        'sNext': '下一页'
#        'sLast': '末页'
#    'fnRowCallback': (row, data, data_index) ->
#      wine_id = data._id
#      status = data.status
#      if status == 0 or status == -1
#        $('td:eq(-3)', row).html '<a href=\'/wines/' + wine_id + '/check\'>审核通过</a>'
#      else
#        $('td:eq(-3)', row).html '<a href=\'/wines/' + wine_id + '/check_out\'>审核不通过</a>'
#
#      $('td:eq(-1)', row).html '<a href=\'/wines/' + wine_id + '/edit\'>修改｜</a>' +
#          '<a href=\'/wines/' + wine_id + '\'>详细｜</a>' +
#          '<a href=\'/wines/' + wine_id + '/mark\'>标签｜</a>' +
#          '<a href=\'/wines/' + wine_id + '/turn_picture\'>轮播图｜</a>' +
#          '<a href=\'/wines/' + wine_id + '\' data-method = \'delete\'>删除</a>'
#      row
#  return

# ---
# generated by js2coffee 2.1.0